### ISSUE TITLE
crused😒

### ISSUE THREAD

**Issue by BDhackers009** [darknethaxor/DH-HackBar#2]
![Screenshot_2021-02-25-17-27-04-46](https://user-images.githubusercontent.com/67186139/109147072-ca6af280-778e-11eb-8ede-c145493e4411.jpg)

**Comment by mdyasinahmedshuvo** [comment]
Please share an screenshot of the topper part, or copy-paste the full crashlog. 🙂

**Comment by masterjavaofficial** [comment]
Please share an screenshot of the topper part, or copy-paste the full crashlog. 🙂

**Comment by BDhackers009** [comment]
hur mia gc te na disi🙄😐😕

**Comment by darknethaxor** [comment]
⚙️⚙️⚙️ 😪😪😪
