### ISSUE TITLE
It doesn't render.

### ISSUE THREAD

**Issue by BreadIsPan** [darknethaxor/DH-HackBar#3]
![Screenshot_2021-04-02-18-01-08-273_com darknethaxor hackbar](https://user-images.githubusercontent.com/40422689/113400957-98782c00-93dd-11eb-9db1-8bc2580c6255.jpg)

I using poco x3 nfc xiaomi with xiaomi.eu custom rom
Hackbar is doesn't render.
Android os is 10.
How to fix that?

**Comment by masterjavaofficial** [comment]
Since DH HackBar Release 1.1, we aren't supporting devices with custom RAM or root privileges for some security issues.

**Comment by masterjavaofficial** [comment]
Since DH HackBar Release 1.1, we aren't supporting devices with root privileges or custom ROMs anymore. We're really sorry for the inconvenience.
