### ISSUE TITLE
Crushing

### ISSUE THREAD

**Issue by C-Joydip** [darknethaxor/DH-HackBar#5]
My device is rooted. I used magisk hide to use DH Hackbar. Now I am facing several crushes when I turn a string into hex. Is it for my root access? If not please solve this

**Comment by masterjavaofficial** [comment]
> My device is rooted. I used magisk hide to use DH Hackbar. Now I am facing several crushes when I turn a string into hex. Is it for my root access? If not please solve this

We’ll try to fix those in next updates.
